### ISSUE TITLE
Uploading a file refreshes the pad twice

### ISSUE THREAD

**Issue by jainendra** [ether/etherpad-lite#3236]
Once a file is uploaded the pad refreshes twice. First it refreshes and place all the text and then again the pad refreshes.

This is not a functionality breaking bug but just ruins the experience of using the pad.

Older versions doesn't seem to have this issue.

**Comment by lpagliari** [comment]
@jainendra when you mention "older versions", are you talking about which versions specifically? Do you know when this stopped working as expected?

**Comment by jainendra** [comment]
@lpagliari I know it works on release/1.3 but its not working in release/1.6.1. I specifically don't know when it stopped. I'll have to take a close in that case. Do you have any idea?

**Comment by JohnMcLear** [comment]
I implemented it, it was required as a clean way of handling import and then refreshing the users view.  It really isn't user experience breaking at all.  It's so rare you do an import anyway....
