### ISSUE TITLE
Error when opening pads after upgrading from 1.7.0 to 1.7.5

### ISSUE THREAD

**Issue by leodeuhh** [ether/etherpad-lite#3575]
Hello,
I am having issues opening pads after upgrading from 1.7.0 to 1.7.5 (git checkout tags).
I am running Ubuntu 18.04 server, node v9.11.2 and plugins ep_adminpads@0.0.12, ep_pad-lister@1.1.3. DB is on MariaDB server.
The log shows the following message:

[2019-03-14 22:21:51.399] [INFO] access - [ENTER] Pad "(removed)": Client sQ5cTxk3j-hCrH1PAAAA with IP "(removed)" entered the pad
[2019-03-14 22:21:51.466] [INFO] ueberDB - Flushed 1 values
[2019-03-14 22:21:51.528] [WARN] client - Uncaught TypeError: hooks.clientPluginNames is not a function -- { errorId: 'Xt9YeMWIwC1CYnuD2GCZ',
  msg: 'Uncaught TypeError: hooks.clientPluginNames is not a function',
  url: '(removed)',
  linenumber: 25,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' }
[2019-03-14 22:21:51.567] [INFO] ueberDB - Flushed 1 values
[2019-03-14 22:22:16.056] [WARN] client - Uncaught TypeError: Cannot read property 'setStateIdle' of null -- { errorId: 'gGbRsc6B6ftb0ztAu29l',
  msg: 'Uncaught TypeError: Cannot read property \'setStateIdle\' of null',
  url: '(removed)',
  linenumber: 3,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' }

Thank you for your help!

**Comment by muxator** [comment]
Hi, at least for the `hooks.clientPluginNames is not a function` error, it may simply be a question of stale cache (which may be a problem in itself, but let's keep it short here).

Could you please try stopping the instance, deleting `var/minified*` and restart again?

The reason for which I am suggesting this, is that the code for `clientPluginNames` is there in **1.7.5**:
https://github.com/ether/etherpad-lite/blob/1.7.5/src/static/js/pluginfw/hooks.js#L141

**Comment by leodeuhh** [comment]
Works perfectly, thank you for the quick reply!
