### ISSUE TITLE
Abiword.js - stdoutCallback is not a function

### ISSUE THREAD

**Issue by ukcb** [ether/etherpad-lite#3456]
I have defined Abiword in my configuration:

`"abiword" : "/usr/bin/abiword"`

I see an error in the log file:
```

[2018-08-12 19:29:07.251] [ERROR] console - TypeError: stdoutCallback is not a function
    at ChildProcess.<anonymous> (/home/etherpad/etherpad-lite/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
```

The export to ms-word, pdf and odf but works fine.

etherpad version: v1.6.6
abiword version : v3.0.2

**Comment by muxator** [comment]
Sorry, I am currently not able to replicate it because my etherpad instance is not able to write into abiword stdin...

**Comment by ukcb** [comment]
@cloudhary I have no solution but abiword works with ep-lite 1.7.5.

**Comment by JohnMcLear** [comment]
If people still experience this problem please let us know and we will re-open.

We recommend trying soffice instead of abiword if you are having problems.

**Comment by jgribonvald** [comment]
I'm getting the same error on debian stretch when I stop the process only

**Comment by JohnMcLear** [comment]
> I'm getting the same error on debian stretch when I stop the process only

Is this if you ``kill`` the abiword PID?

**Comment by jgribonvald** [comment]
> > I'm getting the same error on debian stretch when I stop the process only
> 
> Is this if you `kill` the abiword PID?

when i kill etherpad process and even if no pad are in use

**Comment by JohnMcLear** [comment]
I mean if you kill Etherpad abiword should stop...  I still don't understand this issue.

**Comment by dertuxmalwieder** [comment]
Still happening with current builds on Ctrl+C:

```
[2021-03-18 14:10:43.462] [ERROR] server - TypeError: stdoutCallback is not a function
    at ChildProcess.<anonymous> (/usr/home/etherpad/etherpad-lite/src/node/utils/Abiword.js:86:7)
    at ChildProcess.emit (node:events:378:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2021-03-18 14:10:43.463] [ERROR] server - Error occurred while waiting to exit. Forcing an immediate unclean exit...
```

**Comment by rhansen** [comment]
@dertuxmalwieder This should have been fixed with https://github.com/ether/etherpad-lite/commit/259ee4a987d3db44d3b226c8edebdae86f461245. Are you running current `develop` branch?

**Comment by dertuxmalwieder** [comment]
I updated from 5c9514f9 to cb9f6d67 and I can confirm the fix. Etherpad is moving too fast ... :-) thank you.
