### ISSUE TITLE
crypto.randomUUID error 

### ISSUE THREAD

**Issue by hirisov** [ether/etherpad-lite#5692]
**Describe the bug**
I am using etherpad by building a custom docker image from the official docker image, and then embed it in a Vue application with iframe. In the console I see lot's of

`VM4459 page.js:2 Uncaught (in promise) TypeError: crypto.randomUUID is not a function`

errors. I think this should be related:

https://stackoverflow.com/questions/73205111/nodejs-crypto-randomuuid-is-not-a-function

**To Reproduce**
Embed etherpad from a current docker image in a website.

**Expected behavior**
There should be no such error.

**Server (please complete the following information):**
 - Etherpad version:1.8.18
 - OS: Ubuntu 20.04.5 LTS
 - Node.js version (`node --version`): 16.19.1 in the host
 - npm version (`npm --version`): 8.19.3 in the host
 - Is the server free of plugins: no, there are some plugins installed: ep_adminpads2, ep_align, ep_auth_session, ep_comments_page, ep_embedded_hyperlinks2, ep_etherpad-lite, ep_font_color, ep_framasoft_table_of_contents, ep_headings2, ep_image_upload, ep_linkify2

**Desktop (please complete the following information):**
 - OS: Linux mint

**Additional context**
According to https://nodejs.org/api/crypto.html#cryptorandomuuidoptions I think this should work with 16.19.1, I don't know exactly what node / npm version the docker builds use?
