### ISSUE TITLE
Error with Abiword 3

### ISSUE THREAD

**Issue by formwandler** [ether/etherpad-lite#2301]
I just updates my Linux distro which provides Abiword version 3. Etherpad 1.4.1 worked fine with Abiword 2.8.6 before. But with the new Abiword 3 I get an ERROR when starting Etherpad (when abiword is enabled):

<pre>[2014-11-08 14:18:07.774] [ERROR] console - TypeError: object is not a function
    at ChildProcess.<anonymous> (/opt/etherpad-lite/etherpad-lite/src/node/utils/Abiword.js:95:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:807:12)
[2014-11-08 14:18:07.774] [INFO] console - graceful shutdown...</pre>

Is Abiword 3 proven to work with Etherpad?
