### PR TITLE
fix bug for getPadPlainText

### PR DESCRIPTION
**Pull request by mnagaku**

### CODE REVIEW

**Comment by muxator** [comment]
Thanks for the PR but - please - also [write a test case](https://github.com/ether/etherpad-lite/tree/develop/tests) for the bug you are fixing.
A brief description in the PR text (and in the commit message) could also be useful.

**p.s.**: I understand the [contribution guide](https://github.com/ether/etherpad-lite/blob/379690abbf305d54173c8123ea94eb4d14e4bdf5/CONTRIBUTING.md) does not mention this clearly yet.

**Comment by mnagaku** [comment]
Thanks your comments, muxator.

I wanted to add a test. However, there was no example of helper function test.

I wrote a plugin that uses getPadPlainText().

https://github.com/mnagaku/ep_autotxtexport/blob/master/ep_autotxtexport.js#L21

getPadPlainText() shows the following behavior.

```
[2018-08-11 08:58:59.583] [WARN] console - TypeError: pad.atext is not a function
    at exports.getPadPlainText (/root/etherpad-lite/src/node/utils/ExportHelper.js:25:84)
    at Object.exports.autotxtexport [as hook_fn] (/root/etherpad-lite/node_modules/ep_autotxtexport/ep_autotxtexport.js:21:15)
    at normalizedhook (/root/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/root/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /root/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
    at Function._.map._.collect (/root/etherpad-lite/src/node_modules/underscore/underscore.js:172:24)
    at Object.exports.callAll (/root/etherpad-lite/src/static/js/pluginfw/hooks.js:75:24)
    at Pad.appendRevision (/root/etherpad-lite/src/node/db/Pad.js:110:11)
    at /root/etherpad-lite/src/node/handler/PadMessageHandler.js:775:13
    at /root/etherpad-lite/src/node_modules/async/lib/async.js:610:21
```

I addressed three issues including TypeError. These fixes were formal. These were not logical. I got the desired result with a simple fix.

**Comment by muxator** [comment]
That's true, @mnagaku.

`pad.atext()` should really have been `pad.atext`, and `pad.pool()` -> `pad.pool`, as in the rest of the codebase.

The regression was introduced in 0b5c948549a0 (five years ago!).
